### ISSUE TITLE
how to accommodate CTD casts split into multiple files

### ISSUE THREAD

**Issue by sbeaulieu** [WHOIGit/nes-lter-ims#10]
In cruise AR24B cast 9 got split into two sets of files: 009 and 009b. Presently the bottle summary appears to skip over the 009b, so that when I make the nutrient product 3 bottles get skipped.

**Comment by sbeaulieu** [comment]
This happened again on cruise AR34A in which cast 20 has 2 sets of files, the second of which is labelled "20b". We need to account for these data during the upcast/bottle sampling.

**Comment by joefutrelle** [comment]
Include information about this situation in the README, note when this happened per cruise.

**Comment by joefutrelle** [comment]
Related to #56

**Comment by ecrockford** [comment]
AR24B cast 9 Taylor manually edited to create full ar24b009.btl and .asc. AR34A cast 20 same thing to make complete ar34a020.btl & .asc. See ctd READMEs in vortex for more info. For discrete water sample types, ar24b009 affects many sample types; ar34a020  affects nutrients. both casts have raw files retained in vortex with filenames appended with "_original"

**Comment by joannekoch** [comment]
Fixed by issue #73
