### ISSUE TITLE
consistent handling of missing values for all endpoints

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/nes-lter-ims#116]
Currently a mix of empty cells, "NA", and "NaN" (among others?)

All endpoint CSVs should represent missing values in the same way:

* For string and date/time columns, an empty cell
* For numeric columns, "NaN"

**Comment by joannekoch** [comment]
@joefutrelle, 

Cast values in some end point files are numeric and they are alphanumeric in other files. 
I suggest Cast values are classified as numeric and missing Cast values converted to NaN.  

Please let me know if you agree.
