### ISSUE TITLE
bottle output has columns in alphabetical order

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/nes-lter-ims#16]
they should be in a more semantically meaningful order.

**Comment by joefutrelle** [comment]
https://nes-lter-data.whoi.edu/api/ctd/en608/bottles.csv

**Comment by sbeaulieu** [comment]
Hi, Joe, yes looks like en608 bottles file is in strange order, but the original order appears to be retained for en617.

**Comment by joefutrelle** [comment]
the solution was to use `pd.concat` with `sort=False`. I wasn't using `pd.concat` before for no good reason.
