### ISSUE TITLE
elog parsing retain R2R_Event column

### ISSUE THREAD

**Issue by sbeaulieu** [WHOIGit/nes-lter-ims#17]
NASA EXPORTS is asking PIs to submit data to SeaBASS with R2R event numbers from elog. I think this might set a precedent. We might consider providing this column thru our events API, perhaps as right-most column.

**Comment by joefutrelle** [comment]
Does EXPORTS want edited elogs? We're editing them to "correct" them, which is problematic in various ways, one of which is related to this issue--we add events after the fact, so they don't have R2R event numbers.

**Comment by sbeaulieu** [comment]
Question above: no; I think this request is to be able associate data submitted to SeaBASS to events that happened on a cruise. (I think this is to aid interoperability bw data in different repos.) You are correct in that only those events recorded during a cruise on the 'live' elog would have an R2R event number. If we add events after, our new additions could have 'NA' in R2R_Event column.

**Comment by joefutrelle** [comment]
@sbeaulieu will check this with the upcoming EXPORTS cruise.

**Comment by sbeaulieu** [comment]
Confirmed Yes NASA EXPORTS instructed to record r2r event number to include with their data. Let's please add this column "R2R_Event" to our events API output, perhaps as right-most column. We can put NaN when it is an event that we added as part of our additions workflow.

**Comment by joefutrelle** [comment]
I don't think this is that simple. For instance we're generating CTD deploy events from CTD header files, and these supersede CTD deploy events that were recorded in the elog with event numbers--not sure how to handle that cleanly.

**Comment by ecrockford** [comment]
In terms of CTD's, the r2r_event can be searched for by searching Instrument: CTD, Action: deployment, Cast: cast #, and then get the r2r_event that way? 
FYI, the elog event number is basically the data and time of the entry of the even with 001 at the end. I didn't test this but I think it keeps the same event number even if the event is edited later.

**Comment by sbeaulieu** [comment]
referring back to joe's comment from Jun 7, 2021: we'd also want to retain the Message ID for the CTD deploy events (first version events transect product has NA's).

**Comment by joefutrelle** [comment]
OBE
