### ISSUE TITLE
constrain nearest_station for CTD metadata

### ISSUE THREAD

**Issue by sbeaulieu** [WHOIGit/nes-lter-ims#18]
We had some emails in April 2019 re: casts near LTER stations. I think presently the function nearest_station in stations.py is returning the nearest station based on minimum distance, but I'd like to add a constraint on this distance: if > 1 km then return NA. The reason for this is because we are using nearest_station to associate a CTD cast to a station when station metadata are provided for a cruise. We may want to rename this column 'nearest_station_1km' to be clear in the CTD metadata provided by API.

**Comment by joefutrelle** [comment]
Right now the calculation used to determine nearest station does not use any sort of projection, so the distance is not available in km. I've been planning on fixing this using PostGIS but in the meantime `geopandas` (or just `geopy`) should work.

**Comment by ecrockford** [comment]
I think we should confirm with Heidi that she wants the limit to be 1km

**Comment by sbeaulieu** [comment]
A good use case to 'test' this nearest_station enhancement is for the spring 2019 OOI cruise legs AR34A and AR34B for which Taylor's post-cruise synopsis relates CTD casts to LTER stations. I need to upload a stations metadata file to RDS that includes L1 to L13 but also 7.5, 9.5, 10.5.

**Comment by joefutrelle** [comment]
wrt Taylor's comment above, why not just provide the nearest station column along with a "distance to nearest station" column so people could use whatever radius they wanted?

**Comment by sbeaulieu** [comment]
Great idea!
