### ISSUE TITLE
add columns to indicate OOI sampling on nut and chl REST API products

### ISSUE THREAD

**Issue by sbeaulieu** [WHOIGit/nes-lter-ims#19]
We would like to add two columns to the REST API products for nut and chl: 1 to have categories "LTER", "OOI", and "other" and 2 to have the OOI sample identifier or NaN. This can be derived from the LTER_sample_log.xls. For the nut product there is a single column OOI nut ID. For the chl product there are two columns OOI chla ID and OOI chlb ID (identifiers could be put together with vertical bar ie pipe symbol).

**Comment by joefutrelle** [comment]
Let's split this issue into nut and chl

**Comment by sbeaulieu** [comment]
As discussed on Slack we'd like to include "JP" as another category, thanks
