### ISSUE TITLE
add column for bottle depth to chl REST API product

### ISSUE THREAD

**Issue by sbeaulieu** [WHOIGit/nes-lter-ims#23]
We would like to include a column for bottle depth in the chl API product. This is included in the nutrient API product and is useful because otherwise the end user needs to know to merge with bottle summary data for bottle depth.

**Comment by joefutrelle** [comment]
the bottle summary product also includes date, lat and lon. Should I include those as well?

**Comment by sbeaulieu** [comment]
yes, thanks, date, lat and lon, and depth

**Comment by joefutrelle** [comment]
Done and deployed.
