### ISSUE TITLE
corrected output .mat files do not convert date columns

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/nes-lter-ims#26]
the date column should be datenums but it's being returned as a string.

this looks like it goes back to the `compile_btl_files` function

**Comment by joefutrelle** [comment]
This is not specific to bottle summary files, it has to do with how corrected datasets are treated. In that case the corrected CSV is parsed but date columns are not parsed and turned into datetime64s, so when it gets passed to df_to_mat, it doesn't  know to convert to datenums.

**Comment by joefutrelle** [comment]
@sbeaulieu will evaluate provisional fix

**Comment by sbeaulieu** [comment]
I used the code snippet from our wiki page to webread one CTD cast into variable mytable. The class of entries in the date column is 'char'. Note I was able to use the additional code snippet (for iso8601format) to convert to Matlab serial date number
