### ISSUE TITLE
event log inserts Cast, dtype, and other text into Station column

### ISSUE THREAD

**Issue by sbeaulieu** [WHOIGit/nes-lter-ims#27]
For cruise EN657 there is an error when producing the cleaned event log for CTD cast 019. This is the only cast for which there are two actions in the raw elog (i.e., not just deploy but also recover). The following gets inserted into the "Station" column, replacing the station L7 specified in the raw elog:
Cast
19    L7
19    L7
Name: Station, dtype: object
This issue is different than issue with AR22 elog https://github.com/WHOIGit/nes-lter-ims/issues/9

**Comment by joefutrelle** [comment]
This is a cardinality issue causing the Pandas merge to generate a string representation of a pair of rows.

**Comment by sbeaulieu** [comment]
pre-process elog to remove recover events for CTD casts

**Comment by joefutrelle** [comment]
https://github.com/WHOIGit/nes-lter-ims/blob/290c14d5084783bdc552a0803e9299967f6c6e14/neslter/parsing/elog.py#L114

**Comment by joefutrelle** [comment]
See 42dd24738c3e2c36774c203ee87eb1c22284db02 for fix
