### ISSUE TITLE
event log for EN655 Server Error (500)

### ISSUE THREAD

**Issue by sbeaulieu** [WHOIGit/nes-lter-ims#28]
The API fails to generate a cleaned elog for EN655. I thought the event log parser was only dependent on the CTD header files and underway files being uploaded to RDS raw. I am wondering if this is because there are no CTD .asc files for EN655 in the raw CTD folder (??) (but I do not expect nor could I find this dependency, so it may be something else).

**Comment by joefutrelle** [comment]
Need to check if it's working now.

**Comment by sbeaulieu** [comment]
It is still not working. Looking at the EN655 eventlog csv file, I don't notice anything unusual about it.

**Comment by joefutrelle** [comment]
Need diagnosis.

**Comment by ecrockford** [comment]
There are 2 events that have NaN for GPS time. Would this cause the failure?

**Comment by sbeaulieu** [comment]
Good catch, Taylor! One of these 2 events appears to be a duplicate, so ok to exclude (message ID 115, event 20200728.1200.001 ). The other I checked against EN655_Chl-a_Discrete_UW.xlsx and need to retain. I manually edited the event log on RDS (copied to Google folder), made a note about that in a README on RDS, and voila API works now.
