### ISSUE TITLE
add MVCO to API

### ISSUE THREAD

**Issue by ecrockford** [WHOIGit/nes-lter-ims#32]
Make MVCO available via API. How to organize? Single MVCO file for each data product? File for each "cruise"? For water sample data, if doing per cruise or year or other, make consolidated single file with all sample products?

Many data options to add to API. 
- discrete water sample
- CTD casts
- beam data time series (chl, ctd, cdom, scatter hs/vsf)
- underway Tioga data???

I think primary interest is water sample data (chl, nut, etc)

**Comment by joefutrelle** [comment]
Need a project plan

**Comment by joefutrelle** [comment]
This is a topic that needs further discussion before creating a set of issues about the various tasks and enhancements that will fall out of it
