### ISSUE TITLE
chlorophyll API output NA when missing value for chl or phaeo parameters

### ISSUE THREAD

**Issue by sbeaulieu** [WHOIGit/nes-lter-ims#35]
This is to output NA for chl and phaeo columns when row is in original spreadsheet but no value provided

**Comment by joefutrelle** [comment]
Current behavior is not outputting those rows

**Comment by joefutrelle** [comment]
The rows are dropped here and removing those two columns from the `subset` argument will retain the rows. This may have downstream effects that will need to be dealt with as well.

https://github.com/WHOIGit/nes-lter-ims/blob/9e5dff4caec9c303de1224f4289307f47b1103c7/neslter/parsing/chl.py#L30-L32

**Comment by joefutrelle** [comment]
Looks like `ra`, `rb`, and `blank` being empty should also not result in a row being dropped, which makes sense.
