### ISSUE TITLE
chlorophyll API output quality flag column from original spreadsheet

### ISSUE THREAD

**Issue by sbeaulieu** [WHOIGit/nes-lter-ims#37]
Output Taylor’s quality_flag column because we should consider providing NAs in EDI for flag “3 = very suspicious”

**Comment by joefutrelle** [comment]
This line subsets the columns of the parsed table

https://github.com/WHOIGit/nes-lter-ims/blob/23d8f63367f1aabc3d20db3f2c759eb439fbfd55/neslter/parsing/chl.py#L69

**Comment by joefutrelle** [comment]
This code subsets the columns in the parsed table, and that's likely where the column is being excluded.

https://github.com/WHOIGit/nes-lter-ims/blob/23d8f63367f1aabc3d20db3f2c759eb439fbfd55/neslter/parsing/chl.py#L69-L74
