### ISSUE TITLE
pull CTD files for AR48A

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/nes-lter-ims#38]
https://dlacruisedata.whoi.edu/AR/cruise/AR48-A/ctd/process/

**Comment by ecrockford** [comment]
And probably also these
https://dlacruisedata.whoi.edu/AR/cruise/AR48-A/underway/proc/

https://dlacruisedata.whoi.edu/AR/cruise/AR48-B/ctd/process/
https://dlacruisedata.whoi.edu/AR/cruise/AR48-B/underway/proc/

**Comment by sbeaulieu** [comment]
Thanks, Joe. On vortex I created two folders in raw: ar48a and ar48b.
If you copy files into these folders, I can delete any that we don't need for the API workflow.
The 4 paths are in comments above and repeated here with a note in case you'd like to copy only a subset by filename:
https://dlacruisedata.whoi.edu/AR/cruise/AR48-A/ctd/process/ (only the filenames starting with letter a)
https://dlacruisedata.whoi.edu/AR/cruise/AR48-A/underway/proc/ (only the filenames starting with AR20)
https://dlacruisedata.whoi.edu/AR/cruise/AR48-B/ctd/process/ (only the filenames starting with letter a)
https://dlacruisedata.whoi.edu/AR/cruise/AR48-B/underway/proc/ (only the filenames starting with AR20)

**Comment by sbeaulieu** [comment]
For cruises AR48A and AR48B the underway and CTD data as provided from WHOI DLA are now in the RDS and all API products appear to be working.
