### ISSUE TITLE
events API not working for AR31B

### ISSUE THREAD

**Issue by sbeaulieu** [WHOIGit/nes-lter-ims#42]
I can't figure out why the API is not working for this elog

**Comment by joefutrelle** [comment]
In the raw log, there is a CTD deploy event with a NaN in the cast column.

**Comment by joefutrelle** [comment]
Looks like it should be cast 6

**Comment by sbeaulieu** [comment]
thanks, it's actually two events - I will figure out which is CTD deploy for casts 6 and 7, and then I'll manually edit the csv and replace in RDS

**Comment by joefutrelle** [comment]
Yes, cast 7 appears to be there for the CTD recover event but not for the deploy event

**Comment by joefutrelle** [comment]
@joefutrelle will confirm this is working or not
