### ISSUE TITLE
allow for corrected individual casts

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/nes-lter-ims#44]
(if not already working)

This could help resolve #10

**Comment by joefutrelle** [comment]
What should I do to confirm this?

**Comment by sbeaulieu** [comment]
I confirm that the REST API returns the EN627 cast 2 profile from corrected folder, and that the README is displaying for the corrected folder.

**Comment by joannekoch** [comment]
Closing as confirmation completed.
