### ISSUE TITLE
accommodate lowercase Endeavor cruise identifier when parsing filenames

### ISSUE THREAD

**Issue by sbeaulieu** [WHOIGit/nes-lter-ims#45]
CTD workflow does not work for casts 1-8 on EN661. I think this is because all those filenames have lowercase en661. See:
https://github.com/WHOIGit/nes-lter-ims/blob/master/neslter/parsing/ctd/common.py#L25

**Comment by joefutrelle** [comment]
Should be an easy fix. The larger issue is that while these naming conventions remain inconsistent, we have to keep adding clauses to this code. Any efforts towards consistency in how these files are named, e.g., giving guidance to cruise participants responsible for naming the files, are of course welcome.
