### ISSUE TITLE
Convert READMEs to consistent format (e.g., plain text)

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/nes-lter-ims#47]
@sbeaulieu if you want to fix this on the data side, great. Otherwise I will do some additional development to serve the READMEs in a variety of formats. Right now they all get sent as plain text to the browser, which is not very readable for formats like rtf.

**Comment by sbeaulieu** [comment]
I think this is completed, however please let me know if I missed one (or more) to convert to plain txt.
