### ISSUE TITLE
Treat CTD cast "numbers" as strings instead of integers

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/nes-lter-ims#56]
Given the practice of occasionally naming casts by appending non-numeric characters to the filename, handling cast designations as integers fails in some cases. Rework the API to represent cast "numbers" as strings.

See https://github.com/WHOIGit/nes-lter-ims/issues/40#issuecomment-1450163612 for details on one of these cases.

**Comment by joefutrelle** [comment]
Because processed CTD files use inconsistent naming conventions between cruises, and there are inconsistencies in how non-numeric cast IDs are represented, we will have to add special cases in this block of regexes in order to resolve issues like #40

https://github.com/WHOIGit/nes-lter-ims/blob/ee6489e575945671bd05d793a7b1a4589a37b24d/neslter/parsing/ctd/common.py#L17-L30

**Comment by joannekoch** [comment]
Issue #10  references this issue.
