### ISSUE TITLE
provide access to README files thru API (at least for CTD data)

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/nes-lter-ims#6]
We need an API endpoint for this

**Comment by sbeaulieu** [comment]
specify URL pattern

**Comment by joefutrelle** [comment]
Proposal is to put `?metadata=README` at the end of each URL

**Comment by joefutrelle** [comment]
Here is the code with the complete set of README URL patterns

https://github.com/WHOIGit/nes-lter-ims/blob/79b434285fcf34645adc3165781d3bf56ea3c733/nlweb/api/urls.py#L7
