### ISSUE TITLE
Add .gitattributes configuration to address \r\n issue in CSV files

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/nes-lter-ims#60]
Tracking changes to CSV files is difficult when line endings differ between commits. Address this using a `.gitattributes` configuration to convert to *nix style line endings.

@joannekoch will investigate on `nes-lter-doc-transect`

**Comment by joannekoch** [comment]
The .gitattributes file was added to `nes-lter-doc-transect`. Now when you commit a .txt, .Rmd, .csv, .md, .Rproj, or .xml file to this repository, github will automatically convert all `CR LF` and `CR` line endings to the *nix `LF` line ending.

If this is desired, the .gitattributes file will have to be added to all nes-lter-edi-packages including the minimal-edi-package.

**Comment by ecrockford** [comment]
Yes this is desired! Thanks for implementing this feature. Will definitely be helpful for me. Please add away!
