### ISSUE TITLE
create deployment-nonspecific docker-compose using .env for deployment-specific configuration

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/nes-lter-ims#67]
Having `docker-compose.yml` in vc is problematic because it needs to be configured differently for development and deployment.

Rename `docker-compose.yml` to something like `docker-compose-example.yml` which could then be adapted for various deployments

**Comment by joannekoch** [comment]
May want to have 2 compose files, one for local testing and one for production, i.e. docker-compose-prod.yml and local.yml.

**Comment by joefutrelle** [comment]
good opportunity to move to using `.env` for compose config

**Comment by joefutrelle** [comment]
In fact using `.env` might obviate the need to have two different compose files. The only issue with doing it that way is SSL config for local testing, but that just requires creating a self-signed cert and accepting it when testing the app on localhost.
