### ISSUE TITLE
provide access to column names, definitions, and units

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/nes-lter-ims#8]
initially, for every data type where this information is provided (e.g., CTD headers)

**Comment by sbeaulieu** [comment]
For the CTD headers we could provide a .hdr file, and for the underway data we could provide a text file with the topmost commented lines in the .csv file. In both cases these would be human readable not necessarily parsed.

**Comment by sbeaulieu** [comment]
update to previous comment, for underway data: the column headers for R/V Armstrong are in a separate file in ship-provided_data > underway > doc > CSV_Header.txt.

**Comment by sbeaulieu** [comment]
For "raw all" in the API like nut or chl, a quick fix could be to add the unit as part of the column header. For example, the API could provide "chl_ug_l" as opposed to just "chl".

**Comment by joefutrelle** [comment]
I like that idea for a couple of reasons: 1) it's pretty standard practice, and 2) it would be useful to have it called that even after we're also providing more detailed information about names, definitions, and units.

**Comment by joefutrelle** [comment]
Proposal: add `?metadata=columns` to the end of a URL to get column defs

**Comment by joefutrelle** [comment]
Come up with a different URL scheme

**Comment by joefutrelle** [comment]
Assess datatypes for how this information is provided. E.g., CTD data where it's in the .hdr files.

**Comment by sbeaulieu** [comment]
Add guidance into the Wiki for how to find these metadata per datatype

**Comment by joefutrelle** [comment]
Open specific issues for specific datatypes as needed.
