### ISSUE TITLE
Server Error Thrown for Cruises Metadata Endpoint

### ISSUE THREAD

**Issue by joannekoch** [WHOIGit/nes-lter-ims#85]
https://nes-lter-data.whoi.edu/api/cruises/metadata.csv results in Server Error 500.

Details:
![Capture](https://user-images.githubusercontent.com/65416034/234674877-3d230ff6-e994-44ac-858a-ad8df956d4d0.PNG)

**Comment by joannekoch** [comment]
The issue here is that the `cruise_metadata` function quits processing the list of cruises when there is no elog or elog directory for a cruise. Fix code to skip over these cruises and process all the others.

Also, `elog_path` should not raise an assertion when the event log is not found.

**Comment by joefutrelle** [comment]
Good catch, that should raise a `DataNotFound` error rather than having an assertion fail.
