### ISSUE TITLE
Remove assertions from code run in response to API requests

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/nes-lter-ims#87]
`assert` is used in various places in the code; these assertions should be removed from any code that is called from API endpoints, and replaced with appropriate exceptions like `DataNotFound`, as there's no consistent practice of catching `AssertionError`s, and it's bad practice to do that anyway.

**Comment by joefutrelle** [comment]
https://github.com/WHOIGit/nes-lter-ims/search?q=assert

**Comment by joannekoch** [comment]
Ignore Analysis files and metadata/eml file since these are not currently used.

Delete neslter/parsing/nut/legacy.py and neslter/parsing/chn.py as these are not used either.

**Comment by joefutrelle** [comment]
I think we need `chn` back even though it's not used in the API--there are scripts elsewhere using it.
