### ISSUE TITLE
accommodate "_u" suffix in .asc filename for CTD profile data

### ISSUE THREAD

**Issue by sbeaulieu** [WHOIGit/nes-lter-ims#94]
For cruise EN627: CTD profile data files that include the upcast have a suffix "_u" in the filename (e.g., EN627_028_u.asc).
I would like to copy these files into vortex RDS, retaining these .asc filenames with suffix "_u". 
I don't know if the present REST API code can accommodate the "_u" in the .asc filename. Thanks for checking.
I would like to prioritize this since a team member requested for their research.

**Comment by joannekoch** [comment]
This enhancement to allow .asc file names to have suffix "_u" added to the filename (e.g., EN627_028_u.asc), requires a code change to the API.  Basically, the API will have to be changed to allow filenames with the suffix "_u" and be able to parse the cruise and cast number from the new type of filename.
