### ISSUE TITLE
REST API link not working for nutrient data for AT46 and AR61B

### ISSUE THREAD

**Issue by difontaine** [WHOIGit/nes-lter-ims#95]
AT46 and AR61B nutrient data were available through the REST API a few weeks ago but now the links: 
https://nes-lter-data.whoi.edu/api/nut/at46.csv
https://nes-lter-data.whoi.edu/api/nut/ar61b.csv

Are not working – they report "404" when trying to connect

**Comment by joannekoch** [comment]
In neslter/parsing/files.py, KeyError was changed to DataNotFound error, but in `add_nearest_station` in neslter/workflow/stations.py the KeyError check for Station Metadata was not changed to DataNotFound.
