### ISSUE TITLE
Nutrient API output NA when no matching bottle metadata

### ISSUE THREAD

**Issue by ecrockford** [WHOIGit/nes-lter-ims#97]
Output NA when no matching bottle metadata. Examples of when this would be an issue: bucket samples (not bottle summary), lacking bottle file from manually firing Niskins from CTD deck box which does not create a btl file.

**Comment by joannekoch** [comment]
@ecrockford, is "output NA" referrring to the sample_id column in the nutrient endpoint? For example, ar24a doesn't have a bottle file for cast 1. In this case the sample_ids for ar24a, cast 1, would be set to NA.

**Comment by joannekoch** [comment]
We want to retain content for those columns that derive from LTERnut.xls or LTER_sample_log.xlsx 'raw' spreadsheets even if there is no bottle file for a particular cast. We will do a full, all inclusive merge of the bottle summary for the cruise with LTER_sample_log.xlsx. We will then do a full, all inclusive merge of the result with LTERnut.xls. If there is no bottle file for a cast, then the lat, lon, date, and depth will be set to NA for that cast in the merged data.
